monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: nested
            max_files: 20
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
        security:
            level:    INFO
            type:     stream
            path:     '%kernel.logs_dir%/deprecated.log'
            channels: [php]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
